# Generated by Django 6.0 on 2025-12-23 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0003_alter_juego_plataforma_alter_juego_precio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('favoritos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='favoritos.favoritos')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.juego')),
            ],
            options={
                'unique_together': {('favoritos', 'juego')},
            },
        ),
    ]
