from decimal import Decimal
from catalogo.models import Juego, normalize_title, normalize_platforms

data = [
    ("Baldur's Gate 3", "59.99", "PC, PS5, Xbox Series X, Xbox Series S"),
    ("Elden Ring: Shadow of the Erdtree", "39.99", "PC, PS5, Xbox Series X, Xbox Series S"),
    ("Hogwarts Legacy", "49.99", "PC, PS5, Xbox Series X, Xbox Series S, Switch"),
    ("Starfield", "59.99", "PC, Xbox Series X, Xbox Series S"),
    ("Dragon's Dogma 2", "69.99", "PC, PS5, Xbox Series X, Xbox Series S"),
    ("Black Myth: Wukong", "69.99", "PC, PS5, Xbox Series X, Xbox Series S"),
    ("Call of Duty: Black Ops 6", "69.99", "PC, PS5, Xbox Series X, Xbox Series S"),
    ("Final Fantasy VII Rebirth", "69.99", "PS5"),
    ("The Legend of Zelda: Tears of the Kingdom", "59.99", "Switch"),
    ("Helldivers 2", "39.99", "PC, PS5"),
    ("Cyberpunk 2077", "49.99", "PC, PS5, Xbox Series X, Xbox Series S"),
    ("The Witcher 3: Wild Hunt", "29.99", "PC, PS5, Xbox Series X, Xbox Series S, Switch"),
    ("Red Dead Redemption 2", "39.99", "PC, PS4, Xbox One"),
    ("Grand Theft Auto V", "29.99", "PC, PS5, Xbox Series X, Xbox Series S"),
    ("Resident Evil 4 Remake", "59.99", "PC, PS5, Xbox Series X, Xbox Series S"),
    ("Resident Evil Village", "39.99", "PC, PS5, Xbox Series X, Xbox Series S"),
    ("God of War Ragnarök", "69.99", "PS5, PS4"),
    ("God of War", "39.99", "PC, PS4"),
    ("Marvel's Spider-Man Remastered", "49.99", "PC, PS5"),
    ("Marvel's Spider-Man: Miles Morales", "39.99", "PC, PS5, PS4"),
    ("Horizon Forbidden West", "59.99", "PS5, PS4"),
    ("Horizon Zero Dawn Complete Edition", "19.99", "PC, PS4"),
    ("The Last of Us Part I", "59.99", "PC, PS5"),
    ("The Last of Us Part II Remastered", "49.99", "PS5"),
    ("Ghost of Tsushima Director's Cut", "59.99", "PS5, PS4"),
    ("Sekiro: Shadows Die Twice", "49.99", "PC, PS4, Xbox One"),
    ("Dark Souls III", "29.99", "PC, PS4, Xbox One"),
    ("Bloodborne", "19.99", "PS4"),
    ("Demon's Souls", "69.99", "PS5"),
    ("Armored Core VI: Fires of Rubicon", "59.99", "PC, PS5, Xbox Series X, Xbox Series S, PS4, Xbox One"),
    ("Assassin's Creed Valhalla", "49.99", "PC, PS5, Xbox Series X, Xbox Series S, PS4, Xbox One"),
    ("Assassin's Creed Mirage", "49.99", "PC, PS5, Xbox Series X, Xbox Series S, PS4, Xbox One"),
    ("Far Cry 6", "39.99", "PC, PS5, Xbox Series X, Xbox Series S, PS4, Xbox One"),
    ("Watch Dogs: Legion", "24.99", "PC, PS5, Xbox Series X, Xbox Series S, PS4, Xbox One"),
    ("Tom Clancy's Rainbow Six Siege", "19.99", "PC, PS5, Xbox Series X, Xbox Series S, PS4, Xbox One"),
    ("The Division 2", "19.99", "PC, PS4, Xbox One"),
    ("Forza Horizon 5", "59.99", "PC, Xbox Series X, Xbox Series S, Xbox One"),
    ("Halo Infinite", "59.99", "PC, Xbox Series X, Xbox Series S, Xbox One"),
    ("Gears 5", "29.99", "PC, Xbox One"),
    ("Sea of Thieves", "39.99", "PC, Xbox Series X, Xbox Series S, Xbox One"),
    ("Ori and the Will of the Wisps", "19.99", "PC, Xbox Series X, Xbox Series S, Xbox One, Switch"),
    ("Hades", "24.99", "PC, PS5, Xbox Series X, Xbox Series S, Switch"),
    ("Hades II", "29.99", "PC"),
    ("Stardew Valley", "14.99", "PC, PS4, Xbox One, Switch"),
    ("Terraria", "9.99", "PC, PS4, Xbox One, Switch"),
    ("Minecraft", "29.99", "PC, PS4, Xbox One, Switch"),
    ("Valheim", "19.99", "PC, Xbox Series X, Xbox Series S, Xbox One"),
    ("No Man's Sky", "29.99", "PC, PS5, Xbox Series X, Xbox Series S, PS4, Xbox One, Switch"),
    ("Subnautica", "24.99", "PC, PS4, Xbox One, Switch"),
    ("Subnautica: Below Zero", "29.99", "PC, PS5, Xbox Series X, Xbox Series S, PS4, Xbox One, Switch"),
    ("Bioshock: The Collection", "19.99", "PC, PS4, Xbox One, Switch"),
    ("DOOM Eternal", "39.99", "PC, PS5, Xbox Series X, Xbox Series S, PS4, Xbox One, Switch"),
    ("DOOM (2016)", "19.99", "PC, PS4, Xbox One, Switch"),
    ("Wolfenstein II: The New Colossus", "29.99", "PC, PS4, Xbox One, Switch"),
    ("Dishonored 2", "19.99", "PC, PS4, Xbox One"),
    ("Deathloop", "39.99", "PC, PS5, Xbox Series X, Xbox Series S"),
    ("Prey", "19.99", "PC, PS4, Xbox One"),
    ("Control: Ultimate Edition", "29.99", "PC, PS5, Xbox Series X, Xbox Series S, PS4, Xbox One"),
    ("Alan Wake 2", "59.99", "PC, PS5, Xbox Series X, Xbox Series S"),
    ("Metro Exodus", "29.99", "PC, PS5, Xbox Series X, Xbox Series S, PS4, Xbox One"),
    ("S.T.A.L.K.E.R. 2: Heart of Chornobyl", "69.99", "PC, Xbox Series X, Xbox Series S"),
    ("Lies of P", "59.99", "PC, PS5, Xbox Series X, Xbox Series S, PS4, Xbox One"),
    ("Remnant II", "49.99", "PC, PS5, Xbox Series X, Xbox Series S"),
    ("Diablo IV", "69.99", "PC, PS5, Xbox Series X, Xbox Series S, PS4, Xbox One"),
    ("Path of Exile", "0.00", "PC, PS4, Xbox One"),
    ("Path of Exile 2", "29.99", "PC, PS5, Xbox Series X, Xbox Series S"),
    ("Monster Hunter: World", "29.99", "PC, PS4, Xbox One"),
    ("Monster Hunter Rise", "39.99", "PC, PS5, Xbox Series X, Xbox Series S, Switch"),
    ("Persona 5 Royal", "49.99", "PC, PS5, Xbox Series X, Xbox Series S, Switch"),
    ("Persona 3 Reload", "69.99", "PC, PS5, Xbox Series X, Xbox Series S"),
    ("Like a Dragon: Infinite Wealth", "69.99", "PC, PS5, Xbox Series X, Xbox Series S, PS4, Xbox One"),
    ("Yakuza: Like a Dragon", "29.99", "PC, PS5, Xbox Series X, Xbox Series S, PS4, Xbox One"),
    ("Street Fighter 6", "59.99", "PC, PS5, Xbox Series X, Xbox Series S, PS4"),
    ("Tekken 8", "69.99", "PC, PS5, Xbox Series X, Xbox Series S"),
    ("Mortal Kombat 1", "69.99", "PC, PS5, Xbox Series X, Xbox Series S, Switch"),
    ("EA SPORTS FC 25", "69.99", "PC, PS5, Xbox Series X, Xbox Series S, PS4, Xbox One, Switch"),
    ("NBA 2K25", "69.99", "PC, PS5, Xbox Series X, Xbox Series S, PS4, Xbox One, Switch"),
    ("F1 24", "69.99", "PC, PS5, Xbox Series X, Xbox Series S, PS4, Xbox One"),
    ("Gran Turismo 7", "69.99", "PS5, PS4"),
    ("Mario Kart 8 Deluxe", "59.99", "Switch"),
    ("Super Smash Bros. Ultimate", "59.99", "Switch"),
    ("Animal Crossing: New Horizons", "59.99", "Switch"),
    ("Metroid Dread", "49.99", "Switch"),
    ("Super Mario Odyssey", "49.99", "Switch"),
    ("Kirby and the Forgotten Land", "49.99", "Switch"),
    ("Splatoon 3", "59.99", "Switch"),
    ("Fire Emblem: Three Houses", "49.99", "Switch"),
    ("Xenoblade Chronicles 3", "59.99", "Switch"),
    ("Pokémon Legends: Arceus", "59.99", "Switch"),
    ("Pokémon Scarlet", "59.99", "Switch"),
    ("Pokémon Violet", "59.99", "Switch"),
    ("It Takes Two", "39.99", "PC, PS5, Xbox Series X, Xbox Series S, PS4, Xbox One, Switch"),
    ("A Way Out", "29.99", "PC, PS4, Xbox One"),
    ("Overcooked! 2", "24.99", "PC, PS4, Xbox One, Switch"),
    ("Cuphead", "19.99", "PC, PS4, Xbox One, Switch"),
    ("Celeste", "19.99", "PC, PS4, Xbox One, Switch"),
    ("Hollow Knight", "14.99", "PC, PS4, Xbox One, Switch"),
    ("Dead Cells", "24.99", "PC, PS4, Xbox One, Switch"),
    ("Slay the Spire", "24.99", "PC, PS4, Xbox One, Switch"),
    ("Among Us", "4.99", "PC, PS5, Xbox Series X, Xbox Series S, Switch"),
]

created = 0
updated = 0

for raw_nombre, raw_precio, raw_plat in data:
    nombre = normalize_title(raw_nombre)
    plataforma = normalize_platforms(raw_plat)

    obj, was_created = Juego.objects.update_or_create(
        nombre=nombre,
        defaults={
            "precio": Decimal(raw_precio),
            "plataforma": plataforma,
        },
    )
    if was_created:
        created += 1
    else:
        updated += 1

print(f"OK -> creados: {created}, actualizados: {updated}, total: {len(data)}")
