# Generated by Django 6.0 on 2025-12-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_juego_nombre_alter_juego_plataforma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='plataforma',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='juego',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
