# Generated by Django 6.0 on 2025-12-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_juego_plataforma_alter_juego_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
    ]
